
import AuthProvider from "@/redux/AuthProvider";
import ReduxProvider from "@/redux/ReduxProvider";
import { Inter,Poppins } from "next/font/google";
// import "./globals.css";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const inter = Inter({ subsets: ["latin"] });
export const poppins = Poppins({ subsets: ["latin"], weight:['100','200','300','400','500','600','700','800','900'] });

export const metadata = {
  title: {
    default: "Appoinment management app",
    template: "%s | Rent House"
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <AuthProvider>
            {children}
            <ToastContainer />
          </AuthProvider>
        </ReduxProvider>
        
      </body>
    </html>
  );
}
